- name: Get vault credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Print Password
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/data/my_credentials:password token={{ vault_token }} url=https://172.31.92.119:8200 validate_certs=False')}}"